version: '3'

services:
  mongo:
    container_name: perfomance-mongo
    image: mongo:4.0
    ports:
      - "27017:27017"

  hearth:
    container_name: perfomance-hearth
    image: jembi/hearth:latest
    environment:
      - mongodb__url=mongodb://perfomance-test-db/hearth-dev
      - logger__level=info
      - idGenerator=uuidv4
    ports:
      - "3447:3447"
    depends_on:
      - mongo
    restart: unless-stopped

  influxdb:
    container_name: perfomance-influxdb
    image: influxdb:latest
    environment:
      - logger__level=error
    ports:
      - "8086:8086"
      - "8082:8082"

  chronograf:
    container_name: perfomance-chronograf
    image: chronograf:latest
    environment:
      - logger__level=error
    ports:
      - "8888:8888"
    depends_on:
      - influxdb