language: node_js
node_js:
  - "lts/carbon"
  - "lts/dubnium"
matrix:
  allow_failures:
    - node_js: "lts/dubmium"
dist: xenial
services:
  - mongodb
after_success:
  - npm run test:upload-cov
  - npm run test:load
  - ".travis/build_docker.sh"
before_install:
  - export TZ=Africa/Johannesburg
addon:
  srcclr: true
notifications:
  slack:
    rooms:
      - jembihealthsystems:mlQYVFbijxcZkesCt7G5VBoM
    on_success: change
    on_failure: always

