language: node_js
node_js:
  - "lts/boron"
  - "lts/carbon"
dist: xenial
services:
  - mongodb
after_success:
  - npm run test:upload-cov
  - npm run test:load
  - ".travis/build_docker.sh"
addon:
  srcclr: true
