version: '3'

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.2
    volumes:
      - "./data/mongo:/data/db"

  hearth:
    container_name: hearth
    image: jembi/hearth:latest
    environment:
      mongodb__url: "mongodb://mongo-db/hearth"
    ports:
      - "3447:3447"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3447/api/heartbeat"]
      timeout: 5s
      interval: 10s
      retries: 3
